name: Sync Branch

on:
  push:
    branches:
      - gh-pages  # Define the branch to monitor for changes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Changes
        run: |
          git remote add upstream https://github.com/assurdly/Suretree_Staging_Customer
          git fetch upstream
          git checkout gh-pages
          git merge upstream/gh-pages
          git push origin gh-pages
